panel/urls.py
from django.conf.urls import url
from panel import views

urlpatterns = [
    url(r'^configuration/$',views.configuration,name='configuration'),
    url(r'^configuration/edit/stats/$',views.configuration_stats,name='configuration_stats'),
    url(r'^slider/list/$',views.slider_list,name='slider_list'),
    url(r'^slider/new/$',views.slider_new,name='slider_new'),
    url(r'^slider/edit/(?P<slider_pk>.+)/$',views.slider_edit,name='slider_edit'),
    url(r'^slider/delete/(?P<slider_pk>.+)/$',views.slider_delete,name='slider_delete'),
	url(r'^service/list/$',views.service_list,name='service_list'),
    url(r'^service/new/$',views.service_new,name='service_new'),
    url(r'^service/edit/(?P<service_pk>.+)/$',views.service_edit,name='service_edit'),
    url(r'^service/delete/(?P<service_pk>.+)/$',views.service_delete,name='service_delete'),
    url(r'^service/detail/(?P<service_pk>.+)/$',views.service_detail,name='service_detail'),
	url(r'^pilar/list/$',views.pilar_list,name='pilar_list'),
    url(r'^pilar/new/$',views.pilar_new,name='pilar_new'),
    url(r'^pilar/edit/(?P<pilar_pk>.+)/$',views.pilar_edit,name='pilar_edit'),
    url(r'^pilar/delete/(?P<pilar_pk>.+)/$',views.pilar_delete,name='pilar_delete'),
    url(r'^testimonio/list/$',views.testimony_list,name='testimony_list'),
    url(r'^testimonio/new/$',views.testimony_new,name='testimony_new'),
    url(r'^testimonio/edit/(?P<testimony_pk>.+)/$',views.testimony_edit,name='testimony_edit'),
    url(r'^testimonio/delete/(?P<testimony_pk>.+)/$',views.testimony_delete,name='testimony_delete'),
    url(r'^$',views.team_list,name='team_list'),
    url(r'^equipo/new/$',views.team_new,name='team_new'),
    url(r'^equipo/edit/(?P<team_pk>.+)/$',views.team_edit,name='team_edit'),
    url(r'^equipo/delete/(?P<team_pk>.+)/$',views.team_delete,name='team_delete'),
    url(r'^option/list/$',views.option_list,name='option_list'),
    url(r'^option/new/$',views.option_new,name='option_new'),
    url(r'^option/edit/(?P<option_pk>.+)/$',views.option_edit,name='option_edit'),
    url(r'^option/delete/(?P<option_pk>.+)/$',views.option_delete,name='option_delete'),
    url(r'^post/list/$',views.post_list,name='post_list'),
    url(r'^post/new/$',views.post_new,name='post_new'),
    url(r'^post/edit/(?P<post_pk>.+)/$',views.post_edit,name='post_edit'),
    url(r'^post/delete/(?P<post_pk>.+)/$',views.post_delete,name='post_delete'),
    url(r'^comment/list/(?P<post_pk>.+)/$',views.comment_list,name='comment_list'),
    url(r'^comment/new/(?P<post_pk>.+)/$',views.comment_new,name='comment_new'),
    url(r'^comment/edit/(?P<comment_pk>.+)/$',views.comment_edit,name='comment_edit'),
    url(r'^comment/delete/(?P<comment_pk>.+)/$',views.comment_delete,name='comment_delete'),
    url(r'^comment/child/list/(?P<comment_pk>.+)/$',views.comment_child_list,name='comment_child_list'),
    url(r'^comment/child/(?P<comment_pk>.+)/$',views.comment_child,name='comment_child'),
    url(r'^objetvie/new/(?P<course_pk>.+)/$',views.objetive_new,name='objetive_new'),
    url(r'^objetvie/edit/(?P<course_pk>.+)/(?P<objetive_pk>.+)/$',views.objetive_edit,name='objetive_edit'),
    url(r'^objetvie/delete/(?P<course_pk>.+)/(?P<objetive_pk>.+)/$',views.objetive_delete,name='objetive_delete'),
]

src/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('main.urls',namespace='main')),
    url(r'^auth/', include('authentication.urls',namespace='authentication')),
    url(r'^panel/', include('panel.urls',namespace='panel')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

panel/forms.py
from django import forms
from django.forms import ModelForm, HiddenInput, CharField, TextInput
from panel.models import *
from django.utils.translation import ugettext, ugettext_lazy as _
from panel.functions import add_form_control_class, add_field_control_class,add_field_select_class


class SliderForm(ModelForm):
    class Meta:
        model = Slider
        exclude = ['created_at','updated_at']

    def __init__(self, *args, **kwargs):
        super(SliderForm, self).__init__(*args, **kwargs)
        _instance = kwargs.pop('instance', None)
        add_form_control_class(self.fields)
class ServiceForm(ModelForm):
    class Meta:
        model = Service
        exclude = ['created_at','updated_at']

    def __init__(self, *args, **kwargs):
        super(ServiceForm, self).__init__(*args, **kwargs)
        _instance = kwargs.pop('instance', None)
        add_form_control_class(self.fields)
class PilarForm(ModelForm):
    class Meta:
        model = Pilar
        exclude = ['created_at','updated_at']

    def __init__(self, *args, **kwargs):
        super(PilarForm, self).__init__(*args, **kwargs)
        _instance = kwargs.pop('instance', None)
        add_form_control_class(self.fields)
class TestimonyForm(ModelForm):
    class Meta:
        model = Testimony
        exclude = ['created_at','updated_at']

    def __init__(self, *args, **kwargs):
        super(TestimonyForm, self).__init__(*args, **kwargs)
        _instance = kwargs.pop('instance', None)
        add_form_control_class(self.fields)
class TeamForm(ModelForm):
    class Meta:
        model = Team
        exclude = ['created_at','updated_at']

    def __init__(self, *args, **kwargs):
        super(TeamForm, self).__init__(*args, **kwargs)
        _instance = kwargs.pop('instance', None)
        add_form_control_class(self.fields)
class OptionForm(ModelForm):
    class Meta:
        model = OptionChoise
        exclude = ['created_at','updated_at']

    def __init__(self, *args, **kwargs):
        super(OptionForm, self).__init__(*args, **kwargs)
        _instance = kwargs.pop('instance', None)
        add_form_control_class(self.fields)
class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ['created_at','updated_at']

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        _instance = kwargs.pop('instance', None)
        add_form_control_class(self.fields)
class CourseForm(ModelForm):
    class Meta:
        model = Course
        exclude = ['service','created_at','updated_at']

    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)
        _instance = kwargs.pop('instance', None)
        add_form_control_class(self.fields)
class CourseObjetiveForm(ModelForm):
    class Meta:
        model = CourseObjetive
        exclude = ['course','created_at','updated_at']

    def __init__(self, *args, **kwargs):
        super(CourseObjetiveForm, self).__init__(*args, **kwargs)
        _instance = kwargs.pop('instance', None)
        add_form_control_class(self.fields)
class ConfigurationForm(ModelForm):
    class Meta:
        model = Configuration
        exclude = ['created_at','updated_at']

    def __init__(self, *args, **kwargs):
        super(ConfigurationForm, self).__init__(*args, **kwargs)
        _instance = kwargs.pop('instance', None)
        add_form_control_class(self.fields)
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ['post','father','created_at','updated_at']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        _instance = kwargs.pop('instance', None)
        add_form_control_class(self.fields)

panel/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required
from panel.forms import *
from panel.models import *
# Create your views here.
@login_required
def home(request):
	return render(request,'panel/home.html',locals())
@login_required
def slider_list(request):
	sliders=Slider.objects.all()
	return render(request,'panel/slider/list.html',locals())
@login_required
def slider_new(request):
	title='Crear Slider'
	if request.POST:
		form=SliderForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:slider_list'))
		else:
			message="Revisa la informacion"
	else:
		form=SliderForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def slider_edit(request,slider_pk):
	slider=Slider.objects.get(pk=slider_pk)
	title='Editar Slider {0} - {1}'.format(slider.pk,slider.title)
	if request.POST:
		form=SliderForm(request.POST,request.FILES,instance=slider)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:slider_list'))
		else:
			message='Revisa la informacion'
	else:
		form=SliderForm(instance=slider)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def slider_delete(request,slider_pk):
	slider=Slider.objects.get(pk=slider_pk)
	slider.delete()
	return redirect(reverse('panel:slider_list'))
@login_required
def service_list(request):
	services=Service.objects.all()
	return render(request,'panel/service/list.html',locals())
@login_required
def service_new(request):
	title='Crear Servicio'
	if request.POST:
		form=ServiceForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:service_list'))
		else:
			message="Revisa la informacion"
	else:
		form=ServiceForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def service_edit(request,service_pk):
	service=Service.objects.get(pk=service_pk)
	title='Editar Servicio {0} - {1}'.format(service.pk,service.title)
	if request.POST:
		form=ServiceForm(request.POST,request.FILES,instance=service)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:service_list'))
		else:
			message='Revisa la informacion'
	else:
		form=ServiceForm(instance=service)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def service_delete(request,service_pk):
	service=Service.objects.get(pk=service_pk)
	service.delete()
	return redirect(reverse('panel:service_list'))
@login_required
def service_detail(request,service_pk):
	service=get_object_or_404(Service,pk=service_pk)
	title='Detalle Servicio {0}'.format(service.title)
	try:
		course=Course.objects.get(service__pk=service_pk)
	except Course.DoesNotExist:
		course=None
	if request.POST:
		if course:
			form=CourseForm(request.POST,request.FILES,instance=course)
		else:
			form=CourseForm(request.POST,request.FILES)
		if form.is_valid():
			if course:
				form.save()
			else:
				course=form.save(commit=False)
				course.service=service
				course.save()
			return redirect(reverse('panel:service_detail',kwargs={'service_pk':service.pk}))
		else:
			message='Revisa la informacion'
	else:
		if course:
			form=CourseForm(instance=course)
		else:
			form=CourseForm()
	if course:
		objetives=CourseObjetive.objects.filter(course=course)
		show_table=True
	else:
		objetives=None
		show_table=False
	return render(request,'panel/service/service_detail.html',locals())
@login_required
def pilar_list(request):
	pilars=Pilar.objects.all()
	return render(request,'panel/pilar/list.html',locals())
@login_required
def pilar_new(request):
	title='Crear Pilar de la empresa'
	if request.POST:
		form=PilarForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:pilar_list'))
		else:
			message="Revisa la informacion"
	else:
		form=PilarForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def pilar_edit(request,pilar_pk):
	pilar=Pilar.objects.get(pk=pilar_pk)
	title='Editar Pilar de la empresa {0} '.format(pilar.pk)
	if request.POST:
		form=PilarForm(request.POST,request.FILES,instance=pilar)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:pilar_list'))
		else:
			message='Revisa la informacion'
	else:
		form=PilarForm(instance=pilar)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def pilar_delete(request,pilar_pk):
	pilar=Pilar.objects.get(pk=pilar_pk)
	pilar.delete()
	return redirect(reverse('panel:pilar_list'))
@login_required
def option_list(request):
	options=OptionChoise.objects.all()
	return render(request,'panel/option/list.html',locals())
@login_required
def option_new(request):
	title='Crear Opcion para elegirnos'
	if request.POST:
		form=OptionForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:option_list'))
		else:
			message="Revisa la informacion"
	else:
		form=OptionForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def option_edit(request,option_pk):
	option=OptionChoise.objects.get(pk=option_pk)
	title='Editar Opcion para elegirnos{0} -{1} '.format(option.pk,option.title)
	if request.POST:
		form=OptionForm(request.POST,request.FILES,instance=option)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:option_list'))
		else:
			message='Revisa la informacion'
	else:
		form=OptionForm(instance=option)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def option_delete(request,option_pk):
	option=OptionChoise.objects.get(pk=option_pk)
	option.delete()
	return redirect(reverse('panel:option_list'))


@login_required
def objetive_new(request,course_pk):
	course=Course.objects.get(pk=course_pk)
	title='Crear Objetivo'
	if request.POST:
		form=CourseObjetiveForm(request.POST,request.FILES)
		if form.is_valid():
			objetive=form.save(commit=False)
			objetive.course=course
			objetive.save()
			return redirect(reverse('panel:service_detail',kwargs={'service_pk':course.service.pk}))
		else:
			message="Revisa la informacion"
	else:
		form=CourseObjetiveForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def objetive_edit(request,course_pk,objetive_pk):
	objetive=CourseObjetive.objects.get(pk=objetive_pk)
	course=Course.objects.get(pk=course_pk)

	title='Editar Objetivo'
	if request.POST:
		form=CourseObjetiveForm(request.POST,request.FILES,instance=objetive)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:service_detail',kwargs={'service_pk':course.service.pk}))
		else:
			message='Revisa la informacion'
	else:
		form=CourseObjetiveForm(instance=objetive)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def objetive_delete(request,course_pk,objetive_pk):
	course=Course.objects.get(pk=course_pk)	
	objetive=CourseObjetive.objects.get(pk=objetive_pk)
	objetive.delete()
	return redirect(reverse('panel:service_detail',kwargs={'service_pk':course.service.pk}))
@login_required
def configuration(request):
	configuration=Configuration.objects.all()
	if len(configuration) > 1 or len(configuration) <1:
		for c in configuration:
			c.delete()
		configuration=Configuration()
		configuration.save()
	else:
		configuration=configuration.first()
	return render(request,'panel/configuration.html',locals())

@login_required 
def configuration_stats(request):
	title="Edicion de valores de iniciales"
	configuration=Configuration.objects.all()
	if len(configuration) > 1 or len(configuration) <1:
		for c in configuration:
			c.delete()
		configuration=Configuration()
		configuration.save()
	else:
		configuration=configuration.first()
	if request.POST:
		form=ConfigurationForm(request.POST,request.FILES,instance=configuration)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:configuration'))
		else:
			message="Revise la informacion"
	else:
		form=ConfigurationForm(instance=configuration)
	return render(request,'panel/hooks/form.html',locals())
@login_required
def testimony_list(request):
	testimonies=Testimony.objects.all()
	return render(request,'panel/testimony/list.html',locals())
@login_required
def testimony_new(request):
	title='Crear Testimonio de la empresa'
	if request.POST:
		form=TestimonyForm(request.POST,request.FILES)
		if form.is_valid():
			testimony=form.save()
			if testimony.is_primary:
				ts=Testimony.objects.filter(is_primary=True)
				ts=ts.exclude(pk=testimony.pk)
				for t in ts:
					t.is_primary=False
					t.save()
			return redirect(reverse('panel:testimony_list'))
		else:
			message="Revisa la informacion"
	else:
		form=TestimonyForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def testimony_edit(request,testimony_pk):
	testimony=Testimony.objects.get(pk=testimony_pk)
	title='Editar Testimonio de la empresa {0} '.format(testimony.pk)
	if request.POST:
		form=TestimonyForm(request.POST,request.FILES,instance=testimony)
		if form.is_valid():
			testimony=form.save()
			if testimony.is_primary:
				ts=Testimony.objects.filter(is_primary=True)
				ts=ts.exclude(pk=testimony.pk)
				for t in ts:
					t.is_primary=False
					t.save()
			return redirect(reverse('panel:testimony_list'))
		else:
			message='Revisa la informacion'
	else:
		form=TestimonyForm(instance=testimony)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def testimony_delete(request,testimony_pk):
	testimony=Testimony.objects.get(pk=testimony_pk)
	testimony.delete()
	return redirect(reverse('panel:testimony_list'))

@login_required
def team_list(request):
	members=Team.objects.all()
	return render(request,'panel/team/list.html',locals())
@login_required
def team_new(request):
	title='Crear Miembro de la empresa'
	if request.POST:
		form=TeamForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:team_list'))
		else:

panel/templates/panel/post/comments.html
{% extends 'panel/nav.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'panel/css/compiled/tables.css' %}"/>
    <link href="{% static 'panel/css/lib/jquery.dataTables.css' %}" type="text/css" rel="stylesheet"/>

    <!-- this page specific styles -->
    <link rel="stylesheet" href=" {% static 'panel/css/compiled/datatables.css' %}" type="text/css" media="screen"/>

{% endblock %}
{% block content %}
    <div id="pad-wrapper" class="users-list">
        
        <div class="table-wrapper products-table">
            <div class="row header">
                <h3>Comentarios</h3>
                    <div class="col-md-10 col-sm-12 col-xs-12 pull-right">
                        <a href="{% url 'panel:comment_new' post.pk %}" class="btn-flat success pull-right">
                            <span>&#43;</span>
                            Nuevo Comentario
                        </a>
                    </div>
            </div>
            {% if message %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <strong>Error!</strong> {{ message }} {{ response }}
                </div>
            {% endif %}
            <table id='example'>
                <thead>
                <tr>
                    <th>POST</th>
                    <th><span class="line"></span>Nombre</th>
                    <th><span class="line"></span>Email</th>
                    <th><span class="line"></span>Creado</th>
                    <th><span class="line"></span>Opciones</th>
                    <!--<th><span class="line"></span>Formato</th>-->
                </tr>
                </thead>
                <tbody>
                {% for s in comments %}
                    <tr>
                        <td>{{s.post.pk}}</td>
                        <td>{{s.name}}</td>
                        <td>{{s.email}}</td>
                        <td>{{ s.created_at }}</td>
                        <td>                    
                            <ul class="actions">
                                <li><a href="{% url 'panel:comment_edit' s.pk%}">Editar</a></li>
                                <li><a href="{% url 'panel:comment_delete' s.pk%}">Delete</a></li>
                                <li><a href="{% url 'panel:comment_child_list' s.pk%}">Subcomentarios</a></li>
                               
                            </ul>
                        </td>
                    </tr>
                {% endfor %}
               
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'panel/js/jquery.dataTables.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#example').dataTable({
                "sPaginationType": "full_numbers"
            });
        });
    </script>
{% endblock %}

panel/templates/panel/post/comments_childs.html
{% extends 'panel/nav.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'panel/css/compiled/tables.css' %}"/>
    <link href="{% static 'panel/css/lib/jquery.dataTables.css' %}" type="text/css" rel="stylesheet"/>

    <!-- this page specific styles -->
    <link rel="stylesheet" href=" {% static 'panel/css/compiled/datatables.css' %}" type="text/css" media="screen"/>

{% endblock %}
{% block content %}
    <div id="pad-wrapper" class="users-list">
        
        <div class="table-wrapper products-table">
            <div class="row header">
                <h3>Comentarios Hijos de Comentario {{comment.pk}} </h3>
                    <div class="col-md-10 col-sm-12 col-xs-12 pull-right">
                        <a href="{% url 'panel:comment_child' comment.pk %}" class="btn-flat success pull-right">
                            <span>&#43;</span>
                            Nuevo Comentario
                        </a>
                    </div>
            </div>
            {% if message %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <strong>Error!</strong> {{ message }} {{ response }}
                </div>
            {% endif %}
            <table id='example'>
                <thead>
                <tr>
                    <th>POST</th>
                    <th><span class="line"></span>Nombre</th>
                    <th><span class="line"></span>Email</th>
                    <th><span class="line"></span>Padre</th>
                    <th><span class="line"></span>Creado</th>
                    <th><span class="line"></span>Opciones</th>
                    <!--<th><span class="line"></span>Formato</th>-->
                </tr>
                </thead>
                <tbody>
                {% for s in comments %}
                    <tr>
                        <td>{{s.post}}</td>
                        <td>{{s.name}}</td>
                        <td>{{s.email}}</td>
                        <td>{{s.father}}</td>
                        <td>{{ s.created_at }}</td>
                        <td>                    
                            <ul class="actions">
                                <li><a href="{% url 'panel:comment_edit' s.pk%}">Editar</a></li>
                                <li><a href="{% url 'panel:comment_delete' s.pk%}">Delete</a></li>
                               
                            </ul>
                        </td>
                    </tr>
                {% endfor %}
               
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'panel/js/jquery.dataTables.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#example').dataTable({
                "sPaginationType": "full_numbers"
            });
        });
    </script>
{% endblock %}

panel/templates/panel/post/list.html
{% extends 'panel/nav.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'panel/css/compiled/tables.css' %}"/>
    <link href="{% static 'panel/css/lib/jquery.dataTables.css' %}" type="text/css" rel="stylesheet"/>

    <!-- this page specific styles -->
    <link rel="stylesheet" href=" {% static 'panel/css/compiled/datatables.css' %}" type="text/css" media="screen"/>

{% endblock %}
{% block content %}
    <div id="pad-wrapper" class="users-list">
        
        <div class="table-wrapper products-table">
            <div class="row header">
                <h3>Post BLOG de WAKEUP</h3>
                    <div class="col-md-10 col-sm-12 col-xs-12 pull-right">
                        <a href="{% url 'panel:post_new'%}" class="btn-flat success pull-right">
                            <span>&#43;</span>
                            Nuevo Post
                        </a>
                    </div>
            </div>
            {% if message %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <strong>Error!</strong> {{ message }} {{ response }}
                </div>
            {% endif %}
            <table id='example'>
                <thead>
                <tr>
                    <th>Pk</th>
                    <th><span class="line"></span>Titulo</th>
                    <th><span class="line"></span>Creado</th>
                    <th><span class="line"></span>Opciones</th>
                    <!--<th><span class="line"></span>Formato</th>-->
                </tr>
                </thead>
                <tbody>
                {% for s in posts %}
                    <tr>
                        <td>{{s.pk}}</td>
                        <td>{{s.title}}</td>
                        <td>{{ s.created_at }}</td>
                        <td>                    
                            <ul class="actions">
                                <li><a href="{% url 'panel:post_edit' s.pk%}">Editar</a></li>
                                <li><a href="{% url 'panel:post_delete' s.pk%}">Delete</a></li>
                                <li><a href="{% url 'panel:comment_list' s.pk%}">Comentarios</a></li>
                               
                            </ul>
                        </td>
                    </tr>
                {% endfor %}
               
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'panel/js/jquery.dataTables.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#example').dataTable({
                "sPaginationType": "full_numbers"
            });
        });
    </script>
{% endblock %}