main/urls.py
from django.conf.urls import url
from django.contrib import admin
from main import views

urlpatterns = [
    url(r'^$',views.home2,name='home'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^service/detail/(?P<service_pk>.+)/$',views.service_detail,name='service_detail'),
    url(r'^post/detail/(?P<post_pk>.+)/$',views.post_detail,name='post_detail'),
    url(r'^getservices/$',views.get_services,name='get_services'),
    url(r'^getcontries/$',views.get_contries,name='get_contries'),
    url(r'^getknow/$',views.get_know,name='get_know'),
    url(r'^getstates/(?P<country_pk>.+)/$',views.get_states,name='get_states'),
]

src/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('main.urls',namespace='main')),
    url(r'^auth/', include('authentication.urls',namespace='authentication')),
    url(r'^panel/', include('panel.urls',namespace='panel')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render,redirect,get_object_or_404
from panel.models import *
from panel.forms import CommentForm
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
import json
from src.settings import APPSELOM_URL,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_STORAGE_BUCKET_NAME,TOKEN_APSELOM,LINK_INTRANET
import boto3



# Create your views here.

def home(request):
	return render(request,'main/home.html',locals())

def get_services(request):
	s3_session = boto3.Session(aws_access_key_id=AWS_ACCESS_KEY_ID, aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
	bucket_object = s3_session.resource('s3').Bucket(AWS_STORAGE_BUCKET_NAME).Object("static/main/json/programs.json")
	content = bucket_object.get()['Body'].read()
	json_content = json.loads(content)
	return HttpResponse(json.dumps(json_content),content_type="application/json",status='200')
def get_contries(request):
	s3_session = boto3.Session(aws_access_key_id=AWS_ACCESS_KEY_ID, aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
	bucket_object = s3_session.resource('s3').Bucket(AWS_STORAGE_BUCKET_NAME).Object("static/main/json/contries_get.json")
	content = bucket_object.get()['Body'].read()
	json_content = json.loads(content)
	return HttpResponse(json.dumps(json_content),content_type="application/json",status='200')
def get_know(request):
	s3_session = boto3.Session(aws_access_key_id=AWS_ACCESS_KEY_ID, aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
	bucket_object = s3_session.resource('s3').Bucket(AWS_STORAGE_BUCKET_NAME).Object("static/main/json/conociste.json")
	content = bucket_object.get()['Body'].read()
	json_content = json.loads(content)
	return HttpResponse(json.dumps(json_content),content_type="application/json",status='200')
def get_states(request,country_pk):
	s3_session = boto3.Session(aws_access_key_id=AWS_ACCESS_KEY_ID, aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
	bucket_object = s3_session.resource('s3').Bucket(AWS_STORAGE_BUCKET_NAME).Object("static/main/json/contries.json")
	content = bucket_object.get()['Body'].read()
	json_content=[]
	content= json.loads(content)
	for c in content:
		if c['country_id']==int(country_pk):
			json_content.append(c)
	return HttpResponse(json.dumps(json_content),content_type="application/json",status='200')

def home2(request):
	appselom_url=APPSELOM_URL
	token=TOKEN_APSELOM
	sliders=Slider.objects.filter(is_active=True)
	services=Service.objects.filter(is_active=True)
	pilars=Pilar.objects.all()
	testimonies=Testimony.objects.exclude(is_primary=True)
	options_aux=OptionChoise.objects.filter(is_active=True)
	posts=Post.objects.all()
	options=[]
	cont=1
	intranet=LINK_INTRANET
	testimony_principal=None
	try:
		testimony_principal=Testimony.objects.get(is_primary=True)
	except Testimony.DoesNotExist:
		pass
	testimony_phone=[]
	
	for t in testimonies:
		testimony_phone.append(t)
	if testimony_principal:
		testimony_phone.append(testimony_principal)
	for o in options_aux:
		if cont == options_aux.count() and options_aux.count()%2 !=0:
			o.is_last=True
		options.append(o)
		cont+=1
	members=Team.objects.all()
	configuration=Configuration.objects.all()
	if len(configuration) > 1 or len(configuration) <1:
		for c in configuration:
			c.delete()
		configuration=Configuration()
		configuration.save()
	else:
		configuration=configuration.first()
	return render(request,'main/home2.html',locals())
def service_detail(request,service_pk):
	services=Service.objects.filter(is_active=True)
	service=get_object_or_404(Service,pk=service_pk)
	try:
		course=Course.objects.get(service__pk=service_pk)
	except Course.DoesNotExist:
		course=None
	if course:
		objetives=CourseObjetive.objects.filter(course=course)
		show_objetives=True
	else:
		objetives=None
		show_objetives=False
	intranet=LINK_INTRANET
	return render(request,'main/service/detail.html',locals())

def get_childs(c):
	comments=Comment.objects.filter(father__pk=c.pk)
	if comments.count()<=0:
		return False
	return comments
def get_comments(post):
	comments=Comment.objects.filter(post=post,father__isnull=True)
	for c in comments:
		c.childs=get_childs(c)
	return comments

@csrf_exempt
def post_detail(request,post_pk):
	post=get_object_or_404(Post,pk=post_pk)
	if request.POST:
		data=json.loads(request.POST.get('form') or None)
		child=json.loads(request.POST.get('child') or None)
		if child:
			comment_pk=json.loads(request.POST.get('comment') or None)
			comment=get_object_or_404(Comment,pk=comment_pk)
			form=CommentForm(data)
			if form.is_valid():
				comment_new=form.save(commit=False)
				comment_new.post=post
				comment_new.father=comment
				comment_new.save()
				data['post']=post.pk
				data['success'] = True
				return HttpResponse(json.dumps(data),content_type="application/json",status='200')
			else:
				response=JsonResponse({"errors":form.errors,"error":"Revise el formulario"})
				response.status_code=403
				return response
		else:
			form=CommentForm(data)
			if form.is_valid():
				comment_new=form.save(commit=False)
				comment_new.post=post
				comment_new.save()
				data['post']=post.pk
				data['success'] = True
				return HttpResponse(json.dumps(data),content_type="application/json",status='200')
			else:
				response=JsonResponse({"errors":form.errors,"error":"Revise el formulario"})
				response.status_code=403
				return response
	services=Service.objects.filter(is_active=True)
	comments=get_comments(post)
	intranet=LINK_INTRANET
	count_coments=Comment.objects.all().count()
	return render(request,'main/post/item.html',locals())
def contact(request):
	appselom_url=APPSELOM_URL
	token=TOKEN_APSELOM
	intranet=LINK_INTRANET
	services=Service.objects.filter(is_active=True)
	configuration=Configuration.objects.all()
	if len(configuration) > 1 or len(configuration) <1:
		for c in configuration:
			c.delete()
		configuration=Configuration()
		configuration.save()
	else:
		configuration=configuration.first()
	return render(request,'main/contact.html',locals())

main/templates/main/service/detail.html
{% extends 'main/layout.html'%}
{% load static %}
{% block styles %}
<style type="text/css">
    .service-description p{
        font-size: 19px;

    }
    .service-description{
        font-size: 19px;

    }
</style>
{% endblock %}
{% block content %}
    <section id="page-title" class="text-light"
        {% if service.is_imagen %}
            style="background-image: url('{{service.file_data.url}}'); background-size: cover; background-position: center center;"
        {% else %}
            data-bg-video="{{service.file_data.url}}"
        {% endif %}>
        <div class="container">
            
            <div class="page-title">
                {% if service.title %}
                <h1>{{service.title}}</h1>
                {% endif %}
                {% if service.subtitle %}
                <span>{{service.subtitle}}</span>

                <br>
                {% endif %}
                <a href="{% url 'main:contact' %}" class="btn btn-linkedin  btn-lg" style="margin-top: 10%;">Matriculate HOY</a>
            </div>
        </div>
    </section>

{% if course %}
    <section>
        <div class="container">
            <div class="heading-text heading-section text-center">
                <h2>{{course.name}}</h2>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    
                    <h3>{{course.description}}</h3>
                    <span class="service-description">{{course.description_long|linebreaks}}</span>
                </div>
            </div>
            
        </div>
    </section>
    {% if course.file_metodology %}
     <section class="p-t-150 p-b-150" data-bg-parallax="{{course.file_metodology.url}}">
            <div class="bg-overlay"></div>
            <div class="container container-fullscreen">
                <div class="text-middle text-center">
                    <h1 class=" text-light"><b>METODOLOGÍA</b></h1>
                </div>
            </div>
        </section>
       
    {% else %}
    <section  class="background-blue text-light" style="background-color: #46779C !important;">
        <div class="container text-center">
            <h1><b>METODOLOGÍA</b></h1>
        </div>
    </section>
    {% endif %}
    <section>
        <div class="container text-center" style="background-color: #b1b1b06b; " >
            <div style="padding: 5%;">
            <h2>{{course.metodology_title}}</h2>
            <div class="row text-justify">
                <span class="service-description">{{course.metodology|linebreaks}}</span>
            </div>
            <div class="row">
                <a href="{% url 'main:contact' %}" class="btn btn-linkedin  btn-lg">Matricúlate HOY</a>
            </div>
                
            </div>
        </div>
    </section>
    <section>
        <div class="container text-light" style="background-color: #46779C;">
            
            <div class="row">
                
            <div class="col-md-6" style="padding: 5%;">
                <h1>Te ayudaremos a:</h1>
                <ul>
                    {% for a in objetives %}
                    <li> <span class="service-description">{{a.objetive}}</span></li>
                    {% endfor %}
                </ul>
                <h3>{{course.objetive_slogan}}</h3>
            </div>
            <div class="col-md-6" style="padding: 0;">
                <img src="{{course.file_data.url}}" style="width: 100%;">
            </div>
            </div>
        </div>
    </section>
    {% if course.file_time %}
    <section class="p-t-200 p-b-200" data-bg-parallax="{{course.file_time.url}}">
            <div class="bg-overlay"></div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-9 center text-center text-light">
                        <h1 style="color: #28a745;">{{course.times_slogan}}</h1>
                    </div>
                </div>
            </div>
        </section>
    {% else %}
    <section  class="background-blue" >
        <div class="container text-center">
            <h1 style="color: #28a745;">{{course.times_slogan}}</h1>
        </div>
    </section>
    {% endif %}
    
    <section>
        <div class="container">
                
            <div class="row text-center">
                <div class="col-12">
                    
                <h2 style="color:#4747b3;">Duración de programa: {{course.duration}}</h2>
                </div>
                <div class="col-12">
                    
                    <span class="service-description">{{course.times|linebreaks}}</span>
                </div>
                <div class="col-12">
                    
                <a href="{% url 'main:contact' %}" class="btn btn-linkedin  btn-lg">Matricúlate HOY</a>
                </div>
            </div>
        </div>
    </section>
{% endif %}
{% endblock %}