authentication/urls.py
from django.conf.urls import  url
from django.utils.translation import ugettext as _
from . import views
from django.contrib.auth import views as vi

from authentication.forms import SetPasswordFormEdited, AuthenticationFormEdited


urlpatterns = [
                        url(r'^login/$', vi.login, {
                            'template_name': 'authentication/login.html',
                            'authentication_form': AuthenticationFormEdited,
                            'extra_context': {
                                'page': {
                                    'title': _('Log in'),
                                },
                            }
                        }, name='login'),
                        url(r'^logout/$', vi.logout, {
                            'next_page': '/',
                        }, name='logout'),
                       

                        ]

main/urls.py
from django.conf.urls import url
from django.contrib import admin
from main import views

urlpatterns = [
    url(r'^$',views.home2,name='home'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^service/detail/(?P<service_pk>.+)/$',views.service_detail,name='service_detail'),
    url(r'^post/detail/(?P<post_pk>.+)/$',views.post_detail,name='post_detail'),
    url(r'^getservices/$',views.get_services,name='get_services'),
    url(r'^getcontries/$',views.get_contries,name='get_contries'),
    url(r'^getknow/$',views.get_know,name='get_know'),
    url(r'^getstates/(?P<country_pk>.+)/$',views.get_states,name='get_states'),
]

panel/urls.py
from django.conf.urls import url
from panel import views

urlpatterns = [
    url(r'^configuration/$',views.configuration,name='configuration'),
    url(r'^configuration/edit/stats/$',views.configuration_stats,name='configuration_stats'),
    url(r'^slider/list/$',views.slider_list,name='slider_list'),
    url(r'^slider/new/$',views.slider_new,name='slider_new'),
    url(r'^slider/edit/(?P<slider_pk>.+)/$',views.slider_edit,name='slider_edit'),
    url(r'^slider/delete/(?P<slider_pk>.+)/$',views.slider_delete,name='slider_delete'),
	url(r'^service/list/$',views.service_list,name='service_list'),
    url(r'^service/new/$',views.service_new,name='service_new'),
    url(r'^service/edit/(?P<service_pk>.+)/$',views.service_edit,name='service_edit'),
    url(r'^service/delete/(?P<service_pk>.+)/$',views.service_delete,name='service_delete'),
    url(r'^service/detail/(?P<service_pk>.+)/$',views.service_detail,name='service_detail'),
	url(r'^pilar/list/$',views.pilar_list,name='pilar_list'),
    url(r'^pilar/new/$',views.pilar_new,name='pilar_new'),
    url(r'^pilar/edit/(?P<pilar_pk>.+)/$',views.pilar_edit,name='pilar_edit'),
    url(r'^pilar/delete/(?P<pilar_pk>.+)/$',views.pilar_delete,name='pilar_delete'),
    url(r'^testimonio/list/$',views.testimony_list,name='testimony_list'),
    url(r'^testimonio/new/$',views.testimony_new,name='testimony_new'),
    url(r'^testimonio/edit/(?P<testimony_pk>.+)/$',views.testimony_edit,name='testimony_edit'),
    url(r'^testimonio/delete/(?P<testimony_pk>.+)/$',views.testimony_delete,name='testimony_delete'),
    url(r'^$',views.team_list,name='team_list'),
    url(r'^equipo/new/$',views.team_new,name='team_new'),
    url(r'^equipo/edit/(?P<team_pk>.+)/$',views.team_edit,name='team_edit'),
    url(r'^equipo/delete/(?P<team_pk>.+)/$',views.team_delete,name='team_delete'),
    url(r'^option/list/$',views.option_list,name='option_list'),
    url(r'^option/new/$',views.option_new,name='option_new'),
    url(r'^option/edit/(?P<option_pk>.+)/$',views.option_edit,name='option_edit'),
    url(r'^option/delete/(?P<option_pk>.+)/$',views.option_delete,name='option_delete'),
    url(r'^post/list/$',views.post_list,name='post_list'),
    url(r'^post/new/$',views.post_new,name='post_new'),
    url(r'^post/edit/(?P<post_pk>.+)/$',views.post_edit,name='post_edit'),
    url(r'^post/delete/(?P<post_pk>.+)/$',views.post_delete,name='post_delete'),
    url(r'^comment/list/(?P<post_pk>.+)/$',views.comment_list,name='comment_list'),
    url(r'^comment/new/(?P<post_pk>.+)/$',views.comment_new,name='comment_new'),
    url(r'^comment/edit/(?P<comment_pk>.+)/$',views.comment_edit,name='comment_edit'),
    url(r'^comment/delete/(?P<comment_pk>.+)/$',views.comment_delete,name='comment_delete'),
    url(r'^comment/child/list/(?P<comment_pk>.+)/$',views.comment_child_list,name='comment_child_list'),
    url(r'^comment/child/(?P<comment_pk>.+)/$',views.comment_child,name='comment_child'),
    url(r'^objetvie/new/(?P<course_pk>.+)/$',views.objetive_new,name='objetive_new'),
    url(r'^objetvie/edit/(?P<course_pk>.+)/(?P<objetive_pk>.+)/$',views.objetive_edit,name='objetive_edit'),
    url(r'^objetvie/delete/(?P<course_pk>.+)/(?P<objetive_pk>.+)/$',views.objetive_delete,name='objetive_delete'),
]

src/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('main.urls',namespace='main')),
    url(r'^auth/', include('authentication.urls',namespace='authentication')),
    url(r'^panel/', include('panel.urls',namespace='panel')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

panel/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required
from panel.forms import *
from panel.models import *
# Create your views here.
@login_required
def home(request):
	return render(request,'panel/home.html',locals())
@login_required
def slider_list(request):
	sliders=Slider.objects.all()
	return render(request,'panel/slider/list.html',locals())
@login_required
def slider_new(request):
	title='Crear Slider'
	if request.POST:
		form=SliderForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:slider_list'))
		else:
			message="Revisa la informacion"
	else:
		form=SliderForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def slider_edit(request,slider_pk):
	slider=Slider.objects.get(pk=slider_pk)
	title='Editar Slider {0} - {1}'.format(slider.pk,slider.title)
	if request.POST:
		form=SliderForm(request.POST,request.FILES,instance=slider)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:slider_list'))
		else:
			message='Revisa la informacion'
	else:
		form=SliderForm(instance=slider)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def slider_delete(request,slider_pk):
	slider=Slider.objects.get(pk=slider_pk)
	slider.delete()
	return redirect(reverse('panel:slider_list'))
@login_required
def service_list(request):
	services=Service.objects.all()
	return render(request,'panel/service/list.html',locals())
@login_required
def service_new(request):
	title='Crear Servicio'
	if request.POST:
		form=ServiceForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:service_list'))
		else:
			message="Revisa la informacion"
	else:
		form=ServiceForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def service_edit(request,service_pk):
	service=Service.objects.get(pk=service_pk)
	title='Editar Servicio {0} - {1}'.format(service.pk,service.title)
	if request.POST:
		form=ServiceForm(request.POST,request.FILES,instance=service)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:service_list'))
		else:
			message='Revisa la informacion'
	else:
		form=ServiceForm(instance=service)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def service_delete(request,service_pk):
	service=Service.objects.get(pk=service_pk)
	service.delete()
	return redirect(reverse('panel:service_list'))
@login_required
def service_detail(request,service_pk):
	service=get_object_or_404(Service,pk=service_pk)
	title='Detalle Servicio {0}'.format(service.title)
	try:
		course=Course.objects.get(service__pk=service_pk)
	except Course.DoesNotExist:
		course=None
	if request.POST:
		if course:
			form=CourseForm(request.POST,request.FILES,instance=course)
		else:
			form=CourseForm(request.POST,request.FILES)
		if form.is_valid():
			if course:
				form.save()
			else:
				course=form.save(commit=False)
				course.service=service
				course.save()
			return redirect(reverse('panel:service_detail',kwargs={'service_pk':service.pk}))
		else:
			message='Revisa la informacion'
	else:
		if course:
			form=CourseForm(instance=course)
		else:
			form=CourseForm()
	if course:
		objetives=CourseObjetive.objects.filter(course=course)
		show_table=True
	else:
		objetives=None
		show_table=False
	return render(request,'panel/service/service_detail.html',locals())
@login_required
def pilar_list(request):
	pilars=Pilar.objects.all()
	return render(request,'panel/pilar/list.html',locals())
@login_required
def pilar_new(request):
	title='Crear Pilar de la empresa'
	if request.POST:
		form=PilarForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:pilar_list'))
		else:
			message="Revisa la informacion"
	else:
		form=PilarForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def pilar_edit(request,pilar_pk):
	pilar=Pilar.objects.get(pk=pilar_pk)
	title='Editar Pilar de la empresa {0} '.format(pilar.pk)
	if request.POST:
		form=PilarForm(request.POST,request.FILES,instance=pilar)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:pilar_list'))
		else:
			message='Revisa la informacion'
	else:
		form=PilarForm(instance=pilar)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def pilar_delete(request,pilar_pk):
	pilar=Pilar.objects.get(pk=pilar_pk)
	pilar.delete()
	return redirect(reverse('panel:pilar_list'))
@login_required
def option_list(request):
	options=OptionChoise.objects.all()
	return render(request,'panel/option/list.html',locals())
@login_required
def option_new(request):
	title='Crear Opcion para elegirnos'
	if request.POST:
		form=OptionForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:option_list'))
		else:
			message="Revisa la informacion"
	else:
		form=OptionForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def option_edit(request,option_pk):
	option=OptionChoise.objects.get(pk=option_pk)
	title='Editar Opcion para elegirnos{0} -{1} '.format(option.pk,option.title)
	if request.POST:
		form=OptionForm(request.POST,request.FILES,instance=option)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:option_list'))
		else:
			message='Revisa la informacion'
	else:
		form=OptionForm(instance=option)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def option_delete(request,option_pk):
	option=OptionChoise.objects.get(pk=option_pk)
	option.delete()
	return redirect(reverse('panel:option_list'))


@login_required
def objetive_new(request,course_pk):
	course=Course.objects.get(pk=course_pk)
	title='Crear Objetivo'
	if request.POST:
		form=CourseObjetiveForm(request.POST,request.FILES)
		if form.is_valid():
			objetive=form.save(commit=False)
			objetive.course=course
			objetive.save()
			return redirect(reverse('panel:service_detail',kwargs={'service_pk':course.service.pk}))
		else:
			message="Revisa la informacion"
	else:
		form=CourseObjetiveForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def objetive_edit(request,course_pk,objetive_pk):
	objetive=CourseObjetive.objects.get(pk=objetive_pk)
	course=Course.objects.get(pk=course_pk)

	title='Editar Objetivo'
	if request.POST:
		form=CourseObjetiveForm(request.POST,request.FILES,instance=objetive)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:service_detail',kwargs={'service_pk':course.service.pk}))
		else:
			message='Revisa la informacion'
	else:
		form=CourseObjetiveForm(instance=objetive)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def objetive_delete(request,course_pk,objetive_pk):
	course=Course.objects.get(pk=course_pk)	
	objetive=CourseObjetive.objects.get(pk=objetive_pk)
	objetive.delete()
	return redirect(reverse('panel:service_detail',kwargs={'service_pk':course.service.pk}))
@login_required
def configuration(request):
	configuration=Configuration.objects.all()
	if len(configuration) > 1 or len(configuration) <1:
		for c in configuration:
			c.delete()
		configuration=Configuration()
		configuration.save()
	else:
		configuration=configuration.first()
	return render(request,'panel/configuration.html',locals())

@login_required 
def configuration_stats(request):
	title="Edicion de valores de iniciales"
	configuration=Configuration.objects.all()
	if len(configuration) > 1 or len(configuration) <1:
		for c in configuration:
			c.delete()
		configuration=Configuration()
		configuration.save()
	else:
		configuration=configuration.first()
	if request.POST:
		form=ConfigurationForm(request.POST,request.FILES,instance=configuration)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:configuration'))
		else:
			message="Revise la informacion"
	else:
		form=ConfigurationForm(instance=configuration)
	return render(request,'panel/hooks/form.html',locals())
@login_required
def testimony_list(request):
	testimonies=Testimony.objects.all()
	return render(request,'panel/testimony/list.html',locals())
@login_required
def testimony_new(request):
	title='Crear Testimonio de la empresa'
	if request.POST:
		form=TestimonyForm(request.POST,request.FILES)
		if form.is_valid():
			testimony=form.save()
			if testimony.is_primary:
				ts=Testimony.objects.filter(is_primary=True)
				ts=ts.exclude(pk=testimony.pk)
				for t in ts:
					t.is_primary=False
					t.save()
			return redirect(reverse('panel:testimony_list'))
		else:
			message="Revisa la informacion"
	else:
		form=TestimonyForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def testimony_edit(request,testimony_pk):
	testimony=Testimony.objects.get(pk=testimony_pk)
	title='Editar Testimonio de la empresa {0} '.format(testimony.pk)
	if request.POST:
		form=TestimonyForm(request.POST,request.FILES,instance=testimony)
		if form.is_valid():
			testimony=form.save()
			if testimony.is_primary:
				ts=Testimony.objects.filter(is_primary=True)
				ts=ts.exclude(pk=testimony.pk)
				for t in ts:
					t.is_primary=False
					t.save()
			return redirect(reverse('panel:testimony_list'))
		else:
			message='Revisa la informacion'
	else:
		form=TestimonyForm(instance=testimony)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def testimony_delete(request,testimony_pk):
	testimony=Testimony.objects.get(pk=testimony_pk)
	testimony.delete()
	return redirect(reverse('panel:testimony_list'))

@login_required
def team_list(request):
	members=Team.objects.all()
	return render(request,'panel/team/list.html',locals())
@login_required
def team_new(request):
	title='Crear Miembro de la empresa'
	if request.POST:
		form=TeamForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:team_list'))
		else:

panel/templates/panel/configuration.html
{% extends 'panel/nav.html' %}
{% load static %}
{% block styles %}
<style type="text/css">
 .other-info span{
    font-size: 20px;
    margin-bottom: 5%;
 }
    
</style>
{% endblock%}
{% block content %}
 <!-- upper main stats -->
<div id="main-stats">
	<div class="row">
		
		<div class="pull-right" style="margin-top: 2%;margin-right: 5%;">
			<a href="{% url 'panel:configuration_stats'%}" class="btn-flat default icon-pencil
" style="width: 200px;text-align: center;font-size: 20px;"> Editar</a>
		</div>
	</div>
    <div class="row stats-row">
    	<h2>NUMEROS</h2>
        <div class="col-md-3 col-sm-3 stat">
            <div class="data">
            
                <span class="number">{{configuration.cases_success}}</span>
                Casos de Exito
            </div>
        </div>
        <div class="col-md-3 col-sm-3 stat">
            <div class="data">
                <span class="number">{{configuration.actual_clients}}</span>
                Clientes Actuales
            </div>
        </div>
        <div class="col-md-3 col-sm-3 stat">
            <div class="data">
                <span class="number">{{configuration.post_spain}}</span>
                Programas de Posgrado en España
            </div>
        </div>
        <div class="col-md-3 col-sm-3 stat last">
            <div class="data">
                <span class="number">{{configuration.aprovedd_tesis}} %</span>
                Tesis Aprobadas
            </div>
        </div>
    </div>
    <div class="row stats-row other-info">
        <h2>PRIMER SLIDER</h2>
        <span><b>Titulo de formulario: </b> {{ configuration.form_title }}</span><br>
        <span><b>Titulo Primer Slider: </b> {{ configuration.title_first }}</span><br>
        <span><b>Subtitulo Primer Slider: </b> {{ configuration.subtitle_first }}</span><br>
        <span><b>Multimedia del Primer Slider: </b> <a href="{{ configuration.first_slider.url }}">{{ configuration.first_slider }}</a></span><br>
        <h2>NOSOTROS</h2>
        <span><b>Mision</b><br>
            {{configuration.mision|linebreaks}}
        </span>
        <span><b>Vision</b><br>
            {{configuration.vision|linebreaks}}
        </span>
        <h2>OTRAS CONFIGURACIONES</h2>
        <span><b>Mostrar staff: </b> 
            {% if configuration.show_staff %}
                mostrar
            {% else %}
               no mostrar
            {% endif %}
        </span><br>
        <span><b>Contacto contenido</b><br>
            {{configuration.contact_content|linebreaks}}
        </span>
    </div>
</div>

{% endblock %}

panel/templates/panel/home.html
{% extends 'panel/nav.html' %}
{% load static %}
{% block content %}
hola mundo
{% endblock %}

panel/templates/panel/layout.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <title>WAKEUP</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- bootstrap -->
    <link href="{% static 'panel/css/bootstrap/bootstrap-overrides.css' %}" type="text/css" rel="stylesheet"/>


    <!-- global styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'panel/css/compiled/layout.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'panel/css/compiled/elements.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'panel/css/compiled/icons.css' %}"/>

    <link href="{% static 'panel/css/lib/font-awesome.css' %}" type="text/css" rel="stylesheet"/>
    



    <!-- libraries -->
    <link href="{% static 'panel/css/lib/uniform.default.css' %}" type="text/css" rel="stylesheet"/>
    <link href="{% static 'panel/css/lib/select2.css' %}" type="text/css" rel="stylesheet" />
    <link href="{% static 'panel/css/lib/bootstrap.datepicker.css' %}" type="text/css" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'panel/css/compiled/form-showcase.css' %}" type="text/css"
          media="screen"/>
    


    <!-- this page specific styles -->
    <link rel="stylesheet" href="{% static 'panel/css/compiled/index.css' %}" type="text/css" media="screen"/>

    <!-- open sans font -->
    <!-- libraries -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'/>
    <style type="text/css">
        header {
            margin-bottom: 0px !important;
        }
        #sidebar-nav{
            padding-top: 4% !important;
        }
        #sidebar-nav #dashboard-menu{
            margin-left: 0.1% !important;
        }

    </style>
    {% block styles %}
    {% endblock %}
    <style type="text/css">
        .content{
            overflow: scroll !important;
        }
    </style>


    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->


</head>
<body>
<header class="navbar navbar-inverse" role="banner">
    <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" id="menu-toggler">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="" href="{% url 'main:home' %}">
                <img src="{% static 'main/images/logo.png'%}" width="100" height="50" alt="logo" />
            </a>


    </div>

    <ul class="nav navbar-nav pull-right hidden-xs">
        {% block nav %}
        {% endblock %}
        <li>
            <a href="/" class="hidden-xs hidden-sm">
                Web
            </a>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle hidden-xs hidden-sm" data-toggle="dropdown">
                {% if request.user.is_superuser %}
                    {{ request.user.username }}
                {% else %}
                    {{ request.user.first_name }}
                {% endif %}
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'authentication:logout' %}">Salir</a></li>
            </ul>
        </li>
        <li class="settings hidden-xs hidden-sm">
                <a href="{% url 'panel:configuration' %}" role="button">
                    <i class="icon-cog"></i>
                </a>
            </li>
    </ul>
</header>
    {% block sidebar %}
    {% endblock %}


<div class="content">
    {% block content %}

    {% endblock %}
</div>


<!-- call this page plugins -->

<!-- knob -->
<script src="{% static 'panel/js/wysihtml5-0.3.0.js' %}"></script>
<script src="https://code.jquery.com/jquery-latest.js"></script>
<script src="{% static 'panel/js/bootstrap.min.js' %}"></script>
<script src="{% static 'panel/js/bootstrap.datepicker.js' %}"></script>
<script src="{% static 'panel/js/jquery.uniform.min.js' %}"></script>
<script src="{% static 'panel/js/select2.min.js' %}"></script>
<script src="{% static 'panel/js/theme.js' %}"></script>
<script type="text/javascript">
    $(function () {

        // add uniform plugin styles to html elements
        if(typeof uniform !== 'undefined'){
            $("input:checkbox, input:radio").uniform();
        }
        // select2 plugin for select elements

        // datepicker plugin
        if(typeof datepicker !== 'undefined') {
            $('.input-datepicker').datepicker().on('changeDate', function (ev) {
                $(this).datepicker('hide');
            });
        }
    });
</script>
{% block scripts %}

{% endblock %}
</body>

</html>

panel/templates/panel/nav.html
{% extends 'panel/layout.html' %}
{% load static %}
{% block sidebar %}
<div id="sidebar-nav">
    <ul id="dashboard-menu">
		<li>
			<a href="{% url 'panel:team_list'%}">
			    <i class="icon-user"></i>
			    <span>Equipo</span>
			</a>
		</li>
		<li>
			<a href="{% url 'panel:slider_list'%}">
			    <i class="icon-film"></i>
			    <span>Sliders</span>
			</a>
		</li>
		<li>
			<a href="{% url 'panel:service_list'%}">
			    <i class="icon-group"></i>
			    <span>Servicios</span>
			</a>
		</li>
		<li>
			<a href="{% url 'panel:pilar_list'%}">
			    <i class="icon-pushpin"></i>
			    <span>Pilares</span>
			</a>
		</li>
    	<li>
			<a href="{% url 'panel:option_list'%}">
			    <i class="icon-tasks"></i>
			    <span>Opcion para elegirno</span>
			</a>
		</li>
		<li>
			<a href="{% url 'panel:testimony_list'%}">
			    <i class="icon-quote-left"></i>
			    <span>Testimonios</span>
			</a>
		</li>
    	<li>
			<a href="{% url 'panel:post_list'%}">
			    <i class="icon-print"></i>
			    <span>Blog</span>
			</a>
		</li>
    	
	</ul>
</div>

{% endblock %}